Display all available categories and their associated tasks on the left side of the matrix.
chingu-voyages/v47-tier2-team-19 pull request #25
Opened 2024-01-28 19:17 UTC by bscaer

Display all available categories and their associated tasks on the left side of the matrix and populate the matrix with tasks listed under their respective categories.

See https://github.com/orgs/chingu-voyages/projects/196/views/1?pane=issue&itemId=51292441 and https://github.com/orgs/chingu-voyages/projects/196?pane=issue&itemId=49688423.

![image](https://github.com/chingu-voyages/v47-tier2-team-19/assets/13892406/f76faab9-e5cf-45c8-8d4c-41c188ffb7bd)

2024-01-30 18:53 UTC, komalgill0310 requested changes
Thank you for implementing the task display feature – it's working as expected. I've noticed a naming inconsistency in the interfaces. In the Interfaces.tsx file, the interfaces have names starting with 'I', whereas in the rest of the code files, they don't. To maintain consistency, we should either have all interfaces start with 'I' or none at all. Let me know your thoughts on this. Great job overall!

2024-01-30 18:53 UTC, komalgill0310 commented on src/components/Task.tsx
I believe this interface is defined in the **Interfaces.tsx** file so we can delete this file.

2024-01-30 18:53 UTC, komalgill0310 commented on src/App.tsx
> +// import { useState } from "react";
we can remove the commented code.

2024-01-30 18:53 UTC, komalgill0310 commented on src/components/Interfaces.tsx
I think it might be cleaner if we group the export statements at the end. It can make things more readable and we won't have to use the export keyword for each interface. E.g.: 
```
export {ICategory, IActivity, ITask}
```

2024-01-31 02:17 UTC, bscaer commented on src/components/Interfaces.tsx
I tried to do that but it failed to compile.

2024-01-31 19:49 UTC, PedroEnciso approved these changes
Looks great, Beth!

2024-01-31 21:10 UTC, komalgill0310 requested changes
Thank you for addressing the previous changes. Once the requested modifications are completed, we can proceed with merging them into the development branch.

2024-01-31 21:10 UTC, komalgill0310 commented on src/components/RowHeader.tsx
I noticed that activities, categories, and tasks are being created within their own table bodies. It's recommended to have a single table body, with multiple rows, each containing several table data elements.

I've created a screen recording to illustrate the ideal structure. Although adjusting the structure may temporarily affect the styling, it aligns with the expected table structure. Please review the video, and feel free to correct me if there's any misunderstanding.

Thank you!
           
![voyage47](https://github.com/chingu-voyages/v47-tier2-team-19/assets/80730790/a2158cff-61a6-4459-9129-8e58e9d307a7)

2024-01-31 21:10 UTC, komalgill0310 commented on src/components/Interfaces.tsx
I discovered that using the 'type' keyword when exporting interfaces can help avoid errors. For example:

```typescript
export type { Category, Activity, Task };
```

2024-01-31 21:10 UTC, komalgill0310 commented on src/components/Interfaces.tsx
> +    Tasks: ITask [];
It appears there might be a typo in the code. In the 'Activity' interface, the property should be named 'tasks' instead of 'Tasks'. 

```typescript
interface Activity {
  activityName: string;
  tasks: Task[];
}

2024-01-31 22:31 UTC, bscaer commented on src/components/RowHeader.tsx
What am I looking for in the video?

2024-01-31 22:40 UTC, bscaer commented on src/components/RowHeader.tsx
Fixed

2024-01-31 22:41 UTC, bscaer commented on src/components/Interfaces.tsx
> +    Tasks: ITask [];
Fixed

2024-02-01 02:56 UTC, komalgill0310 approved these changes
it looks good, Thank you for updating your code.

2024-02-01 02:59 UTC, merged

2024-02-01 03:00 UTC, komalgill0310 commented
Closing this PR as it has been merged into Development.